=== artchoupaut/Testng_XML_Generator/testngGenerator/env_integration/integration.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT datasets (devices*, environments*, testcases*)>
<!ELEMENT devices (device*)>
<!ELEMENT device EMPTY >
<!ATTLIST device name CDATA #REQUIRED os CDATA #REQUIRED version CDATA #REQUIRED>
<!ELEMENT environments (environment*)>
<!ELEMENT environment EMPTY >
<!ATTLIST environment value CDATA #REQUIRED>
<!ELEMENT testcases (testcase*)>
<!ELEMENT testcase EMPTY >
<!ATTLIST testcase value CDATA #REQUIRED>

=== artchoupaut/Testng_XML_Generator/testngGenerator/env_integration/integration.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE datasets SYSTEM "integration.dtd">
<datasets>
	<devices>
		<device name='iPhone 11' os='IOS' version='15.6'/>
		<device name='iPhone 14 Pro Max' os='IOS' version='16'/>
		<device name='Google Pixel 6' os='ANDROID' version='12.0'/>
	</devices>
	<environments>
		<environment value='staging'/>
		<environment value='uat'/>
		<environment value='preprod'/>
	</environments>
	<testcases>
		<testcase value='Initial'/>
		<testcase value='Drawing'/>
		<testcase value='PinchBalloons'/>
		<testcase value='Login'/>
		<testcase value='AchievementContribution'/>
		<testcase value='DailyWalk'/>
		<testcase value='TapTap'/>
		<testcase value='DailyCheckIn'/>
		<testcase value='BalanceAndUTurn'/>
		<testcase value='symbolsAndNumbers'/>
		<testcase value='PDFunctional'/>
		<testcase value='Typing'/>
		<testcase value='SixMinuteWalk'/>
	</testcases>
</datasets>
